platform :ios, '8.0'

use_frameworks!

target “Flashcard Touch” do

pod 'SCLAlertView'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod ‘Google/Analytics'
pod 'GoogleSignIn'
pod 'DatePickerDialog'
pod 'Kingfisher', '~> 3.0'
pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
pod "PagingMenuController"
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.0'
end
end
end
end
